---
deployment:
  tasks:
    - export REPO_DIR=/home/arunbhatiaias/repositories/arunbhatia
    - export DEPLOY_DIR=/home/arunbhatiaias/public_html
    - rm -rf $DEPLOY_DIR/*
    - cp -R $REPO_DIR/* $DEPLOY_DIR/
    - rm -f $DEPLOY_DIR/.cpanel.yml
    - rm -rf $DEPLOY_DIR/.git
